### ISSUE TITLE
more information...?

### ISSUE THREAD

**Issue by kwalker99** [julienchevalley/k0ntr0l#1]
Hi Julien

It's nice you have finally open sourced K0ntr0l, but where is the readme and introduction detailing the build process? 

Also why not include the original release as binary with the 1000 or so patterns?

Kev

**Comment by julienchevalley** [comment]
Hi Kev, you are right a readme would be nice. As far as the build process goes it is simply a matter of opening the solution file (.sln) in Visual Studio and hitting F5... I can help you if you have more specific issues, but I am no longer investing any time in the development of the project. The patterns can be obtained by downloading an evaluation version of AudioRealism's Bassline. https://www.audiorealism.se/audiorealism-bass-line-3.html
